nba_com_stage:
  tbl_game_info:
    columns:
      - name: game_id
        sql_type: Integer
        python_type: int
        primary_key: true
      - name: game_date
        sql_type: String
        python_type: str
      - name: season_year
        sql_type: Integer
        python_type: Int64
      - name: season_type
        sql_type: String
        python_type: str
      - name: attendance
        sql_type: Integer
        python_type: Int64
      - name: sellout
        sql_type: Integer 
        python_type: Int64 
      - name: duration
        sql_type: Integer
        python_type: Int64
      - name: game_label
        sql_type: String
        python_type: str
      - name: game_sublabel
        sql_type: String
        python_type: str
      - name: series_game_number
        sql_type: String
        python_type: str
      - name: series_text
        sql_type: String
        python_type: str
      - name: home_team_id
        sql_type: Float
        python_type: float
      - name: home_team_city
        sql_type: String
        python_type: str
      - name: home_team_name
        sql_type: String
        python_type: str
      - name: away_team_id
        sql_type: Float
        python_type: float
      - name: away_team_city
        sql_type: String
        python_type: str
      - name: away_team_name
        sql_type: String
        python_type: str
      - name: home_team_score
        sql_type: Integer
        python_type: Int64
      - name: away_team_score
        sql_type: Integer
        python_type: Int64
      - name: final_quarter
        sql_type: String
        python_type: str
      - name: national_tv_broadcast
        sql_type: String
        python_type: str
      - name: source_file
        sql_type: String
        python_type: str
        unique: true
  tbl_player:
    columns:
      - name: game_id
        sql_type: Integer
        python_type: int
        foreign_key: nba_com_stage.tbl_game_info.game_id
        primary_key: true
      - name: player_id
        sql_type: Integer
        python_type: int
        primary_key: true
      - name: first_name
        sql_type: String
        python_type: str
      - name: last_name
        sql_type: String
        python_type: str
      - name: source_file
        sql_type: String
        python_type: str
  tbl_box:
    columns:
      - name: game_id
        sql_type: Integer
        python_type: Int64
        foreign_key: nba_com_stage.tbl_game_info.game_id
        primary_key: true
      - name: player_id
        sql_type: Integer
        python_type: Int64
        primary_key: true
      - name: status
        sql_type: String
        python_type: str
      - name: seconds
        sql_type: Integer
        python_type: Int64
      - name: field_goals_made
        sql_type: Integer
        python_type: Int64
      - name: field_goals_attempted
        sql_type: Integer
        python_type: Int64
      - name: three_pointers_made
        sql_type: Integer
        python_type: Int64
      - name: three_pointers_attempted
        sql_type: Integer
        python_type: Int64
      - name: free_throws_made
        sql_type: Integer
        python_type: Int64
      - name: free_throws_attempted
        sql_type: Integer
        python_type: Int64
      - name: rebounds_offensive
        sql_type: Integer
        python_type: Int64
      - name: rebounds_defensive
        sql_type: Integer
        python_type: Int64
      - name: rebounds_total
        sql_type: Integer
        python_type: Int64
      - name: assists
        sql_type: Integer
        python_type: Int64
      - name: steals
        sql_type: Integer
        python_type: Int64
      - name: blocks
        sql_type: Integer
        python_type: Int64
      - name: turnovers
        sql_type: Integer
        python_type: Int64
      - name: fouls_personal
        sql_type: Integer
        python_type: Int64
      - name: points
        sql_type: Integer
        python_type: Int64
      - name: plus_minus_points
        sql_type: Integer
        python_type: Int64
      - name: source_file
        sql_type: String
        python_type: str